<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Cylinders</h1><p class="text-secondary mb-0">Inventory with derived status and movement history.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Add Cylinder</button></div>
<div class="card shadow-sm"><div class="card-body"><div class="row g-2 mb-3"><div class="col-md-3"><select id="group" class="form-select"><option value="0">All groups</option><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['code'].' - '.$g['name'].' ('.$g['capacity_kg'].' kg)')?></option><?php endforeach;?></select></div><div class="col-md-5"><input id="search" class="form-control" placeholder="Search cylinder or group"></div></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Code</th><th>Group</th><th>Gas / Capacity</th><th>Location</th><th>Status</th><th>Condition</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="modal"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5>Add Cylinder</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select name="group_id" class="form-select mb-2" required><?php foreach($groups as $g):?><option value="<?=$g['id']?>"><?=e($g['code'].' - '.$g['name'])?></option><?php endforeach;?></select><select name="code_mode" id="codeMode" class="form-select mb-2"><option>AUTO</option><option>MANUAL</option></select><input name="code" id="code" class="form-control mb-2" placeholder="Manual code"><input name="gas_kg" class="form-control mb-2" inputmode="decimal" value="0.000" placeholder="Initial gas kg" required><select name="condition_code" class="form-select"><option>GOOD</option><option>DAMAGED</option></select></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<div class="modal fade" id="history"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="historyTitle">Cylinder History</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div id="historyBody"></div></div></div></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'),JSON_THROW_ON_ERROR)?>;
function esc(v){return $('<div>').text(v??'').html();}
function load(){$.getJSON(b+'cylinders/data',{group_id:$('#group').val(),search:$('#search').val()}).done(r=>{let x=$('#rows').empty();(r.data.rows||[]).forEach(v=>x.append('<tr><td>'+esc(v.code)+'</td><td>'+esc(v.group_name)+'</td><td>'+Number(v.gas_kg).toFixed(3)+' / '+Number(v.capacity_kg).toFixed(3)+'</td><td>'+v.location+'</td><td>'+v.status+'</td><td>'+v.condition_code+'</td><td><button class="btn btn-sm btn-outline-secondary hist" data-id="'+v.id+'">History</button>'+(v.active&&v.location!=='SOLD'?'<button class="btn btn-sm btn-outline-danger del ms-1" data-id="'+v.id+'">Delete</button>':'')+'</td></tr>'))}).fail(x=>alert(x.responseJSON?.message||'Load failed'))}
$('#codeMode').change(function(){$('#code').prop('disabled',this.value==='AUTO')}).trigger('change');
$('#form').submit(function(e){e.preventDefault();$.post(b+'cylinders',$(this).serialize()).done(r=>{alert(r.message);if(r.ok)location.reload()}).fail(x=>alert(x.responseJSON?.message||'Save failed'))});
$(document).on('click','.hist',function(){$.getJSON(b+'cylinders/'+$(this).data('id')+'/history').done(r=>{let c=r.data.cylinder,h='<div><strong>'+esc(c.code)+'</strong> · '+esc(c.status)+' · '+esc(c.location)+'</div><hr><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Date</th><th>Type</th><th>Gas</th><th>From</th><th>To</th><th>Rate</th><th>User</th></tr></thead><tbody>';(r.data.movements||[]).forEach(m=>h+='<tr><td>'+esc(m.created_at)+'</td><td>'+esc(m.movement_type)+'</td><td>'+esc(m.before_gas_kg)+' → '+esc(m.after_gas_kg)+'</td><td>'+m.from_location+'</td><td>'+m.to_location+'</td><td>'+esc(m.rate||'')+'</td><td>'+esc(m.user_name||'')+'</td></tr>');h+='</tbody></table></div>';$('#historyBody').html(h);bootstrap.Modal.getOrCreateInstance(document.getElementById('history')).show()})});
$(document).on('click','.del',function(){if(!confirm('Delete this cylinder?'))return;$.post(b+'cylinders/'+$(this).data('id')+'/delete',{}).done(r=>{alert(r.message);load()}).fail(x=>alert(x.responseJSON?.message||'Delete failed'))});
$('#group').change(load);$('#search').keyup(load);load();});
</script>