<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h1 class="h3 mb-1">Cylinders</h1><p class="text-secondary mb-0">Physical cylinder inventory and derived status.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Add Cylinder</button></div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm"><div class="card-body"><input id="search" class="form-control mb-3" placeholder="Search cylinder or group"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Code</th><th>Group</th><th>Gas / Capacity</th><th>Location</th><th>Status</th><th>Condition</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="modal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5 id="title">Add Cylinder</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id" id="id"><select name="group_id" id="group" class="form-select mb-2" required></select><div id="codeModeWrap"><select name="code_mode" class="form-select mb-2"><option>AUTO</option><option>MANUAL</option></select><input name="code" class="form-control mb-2" placeholder="Manual code"></div><input name="gas_kg" id="gas" class="form-control mb-2" inputmode="decimal" value="0" placeholder="Gas kg" required><select name="condition_code" id="condition" class="form-select mb-2"><option>GOOD</option><option>DAMAGED</option></select><textarea name="notes" class="form-control" placeholder="Notes"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<div class="modal fade" id="historyModal" tabindex="-1"><div class="modal-dialog modal-xl"><div class="modal-content"><div class="modal-header"><h5 id="historyTitle">Cylinder History</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Date</th><th>Movement</th><th>Gas</th><th>From</th><th>To</th><th>Customer</th><th>Document</th></tr></thead><tbody id="historyRows"></tbody></table></div></div></div></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'))?>;function esc(v){return $('<div>').text(v??'').html();}function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}
function loadGroups(){ $.getJSON(b+'cylinder-groups/data',{limit:100},r=>{const s=$('#group').empty();(r.data.rows||[]).forEach(x=>s.append(new Option(x.code+' - '+x.name+' ('+x.capacity_kg+' kg)',x.id)));});}
function load(){ $.getJSON(b+'cylinders/data',{search:$('#search').val(),limit:100},r=>{const x=$('#rows').empty();(r.data.rows||[]).forEach(a=>x.append('<tr><td>'+esc(a.code)+'</td><td>'+esc(a.group_name)+'</td><td>'+Number(a.gas_kg).toFixed(3)+' / '+Number(a.capacity_kg).toFixed(3)+'</td><td>'+esc(a.location)+'</td><td>'+esc(a.status)+'</td><td>'+esc(a.condition_code)+'</td><td><button class="btn btn-sm btn-outline-secondary history" data-id="'+a.id+'" data-code="'+esc(a.code)+'">History</button> <button class="btn btn-sm btn-outline-primary edit" data-id="'+a.id+'">Edit</button> <button class="btn btn-sm btn-outline-secondary deactivate" data-id="'+a.id+'">Deactivate</button> <button class="btn btn-sm btn-outline-danger delete" data-id="'+a.id+'">Delete</button></td></tr>'));});}
$('#search').on('keyup',load);$('#codeModeWrap select').on('change',function(){$('[name=code]').prop('disabled',this.value==='AUTO');});
$('#form').on('submit',function(e){e.preventDefault();const id=$('#id').val();$.post(id?b+'cylinders/update':b+'cylinders',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){bootstrap.Modal.getInstance(document.getElementById('modal')).hide();load();}}).fail(x=>msg(x.responseJSON?.message||'Save failed','danger'));});
$('#rows').on('click','.adjust',function(){const id=$(this).data('id');const gas=prompt('New gas kg');if(gas===null)return;const reason=prompt('Mandatory adjustment reason');if(!reason)return;$.post(b+'cylinders/adjust',{id,gas_kg:gas,reason}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#rows').on('click','.history',function(){$('#historyTitle').text('Cylinder History — '+$(this).data('code'));$.getJSON(b+'cylinders/history',{id:$(this).data('id')},r=>{const x=$('#historyRows').empty();(r.data||[]).forEach(a=>x.append('<tr><td>'+esc(a.created_at)+'</td><td>'+esc(a.movement_type)+'</td><td>'+Number(a.before_gas_kg).toFixed(3)+' → '+Number(a.after_gas_kg).toFixed(3)+'</td><td>'+esc(a.from_location)+'</td><td>'+esc(a.to_location)+'</td><td>'+esc(a.customer_name||'')+'</td><td>'+esc((a.source_document_type||'')+' '+(a.source_document_id||''))+'</td></tr>'));new bootstrap.Modal(document.getElementById('historyModal')).show();});});
$('#rows').on('click','.edit',function(){const id=$(this).data('id');$.getJSON(b+'cylinders/data',{search:'',limit:100},r=>{const a=(r.data.rows||[]).find(x=>Number(x.id)===Number(id));if(!a)return;$('#title').text('Edit Cylinder');$('#id').val(a.id);$('#group').val(a.group_id).prop('disabled',true);$('#codeModeWrap').hide();$('#gas').val(a.gas_kg).prop('disabled',true);$('#condition').val(a.condition_code);$('[name=notes]').val(a.notes||'');new bootstrap.Modal(document.getElementById('modal')).show();});});
$('#rows').on('click','.deactivate',function(){if(!confirm('Deactivate this cylinder?'))return;$.post(b+'cylinders/deactivate',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#rows').on('click','.delete',function(){if(!confirm('Delete this cylinder? Deletion is allowed only when unused.'))return;$.post(b+'cylinders/delete',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#modal').on('hidden.bs.modal',function(){$('#form')[0].reset();$('#id').val('');$('#group').prop('disabled',false);$('#gas').prop('disabled',false);$('#codeModeWrap').show();$('#title').text('Add Cylinder');$('#codeModeWrap select').val('AUTO').trigger('change');});
loadGroups();load();$('#codeModeWrap select').trigger('change');});
</script>