<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3">
<div><h1 class="h3 mb-1">Parties</h1><p class="text-secondary mb-0">Customers, suppliers and referees.</p></div>
<div class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?=e(url('/parties/import-template?type=parties'))?>">Excel Template</a><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#partyModal">Add Party</button></div>
</div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm mb-3"><div class="card-body"><div class="row g-2"><div class="col-md-3"><select id="partyType" class="form-select"><option value="CUSTOMER">Customers</option><option value="SUPPLIER">Suppliers</option><option value="REFEREE">Referees</option></select></div><div class="col-md-5"><input id="partySearch" class="form-control" placeholder="Search code, name or phone"></div></div></div></div>
<div class="card shadow-sm"><div class="card-body"><div class="table-responsive"><table class="table table-sm align-middle" id="partyTable"><thead><tr><th>Code</th><th>Name</th><th>Phone</th><th>Balance</th><th>Credit</th><th>Status</th><th></th></tr></thead><tbody></tbody></table></div></div></div>
<div class="card shadow-sm mt-3"><div class="card-header"><strong>Excel Import</strong></div><div class="card-body"><form id="importForm" enctype="multipart/form-data" class="row g-2 align-items-end"><div class="col-md-7"><input name="file" type="file" accept=".xlsx" class="form-control" required></div><input type="hidden" name="type" value="parties"><div class="col-md-3"><button class="btn btn-outline-primary w-100">Preview</button></div></form><div id="preview" class="d-none mt-3"><div id="summary" class="alert alert-info"></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Row</th><th>Code</th><th>Name</th><th>Type</th><th>Result</th></tr></thead><tbody id="previewRows"></tbody></table></div><button id="commit" class="btn btn-success" disabled>Commit Valid Rows</button></div></div></div>
<div class="modal fade" id="partyModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="partyForm"><div class="modal-header"><h5 id="modalTitle">Add Party</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id" id="partyId"><input type="hidden" name="active" id="partyActive" value="1"><input name="code" id="partyCode" class="form-control mb-2" placeholder="Code" required><select name="party_type" id="partyTypeForm" class="form-select mb-2"><option>CUSTOMER</option><option>SUPPLIER</option><option>REFEREE</option></select><input name="name" id="partyName" class="form-control mb-2" placeholder="Name" required><input name="phone" id="partyPhone" class="form-control mb-2" placeholder="Phone"><textarea name="address" id="partyAddress" class="form-control mb-2" placeholder="Address"></textarea><select name="allow_credit" id="partyCredit" class="form-select mb-2"><option value="0">Credit not allowed</option><option value="1">Credit allowed</option></select><input name="credit_limit" id="partyLimit" class="form-control mb-2" value="0.00" placeholder="Credit limit"><textarea name="notes" id="partyNotes" class="form-control" placeholder="Notes"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<script>
$(function(){
 const b=<?=json_encode(url('/'))?>;let validRows=[];
 function esc(v){return $('<div>').text(v??'').html();}function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}
 function load(){$.getJSON(b+'parties/data',{type:$('#partyType').val(),search:$('#partySearch').val(),limit:100},r=>{const body=$('#partyTable tbody').empty();(r.data.rows||[]).forEach(a=>body.append('<tr><td>'+esc(a.code)+'</td><td>'+esc(a.name)+'</td><td>'+esc(a.phone||'')+'</td><td>'+Number(a.current_balance||0).toFixed(2)+'</td><td>'+Number(a.credit_limit||0).toFixed(2)+'</td><td>'+esc(a.active?'Active':'Inactive')+'</td><td><button class="btn btn-sm btn-outline-primary edit" data-json=''+JSON.stringify(a).replace(/'/g,'&apos;')+'\'>Edit</button> <button class="btn btn-sm btn-outline-secondary deactivate" data-id="'+a.id+'">Deactivate</button></td></tr>'));});}
 $('#partyType,#partySearch').on('change keyup',load);
 $('#partyForm').on('submit',function(e){e.preventDefault();const id=$('#partyId').val();const url=id?b+'parties/update':b+'parties';$.post(url,$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){bootstrap.Modal.getInstance(document.getElementById('partyModal')).hide();load();}}).fail(x=>msg(x.responseJSON?.message||'Save failed','danger'));});
 $('#partyTable').on('click','.edit',function(){const a=JSON.parse($(this).attr('data-json').replace(/&apos;/g,"'"));$('#modalTitle').text('Edit Party');$('#partyId').val(a.id);$('#partyCode').val(a.code).prop('disabled',true);$('#partyTypeForm').val(a.party_type).prop('disabled',true);$('#partyName').val(a.name);$('#partyPhone').val(a.phone||'');$('#partyAddress').val(a.address||'');$('#partyCredit').val(a.allow_credit);$('#partyLimit').val(a.credit_limit);$('#partyNotes').val(a.notes||'');new bootstrap.Modal(document.getElementById('partyModal')).show();});
 $('#partyTable').on('click','.deactivate',function(){if(!confirm('Deactivate this party?'))return;$.post(b+'parties/deactivate',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
 $('#partyModal').on('hidden.bs.modal',function(){$('#partyForm')[0].reset();$('#partyId').val('');$('#partyCode').prop('disabled',false);$('#partyTypeForm').prop('disabled',false);$('#partyActive').val('1');$('#modalTitle').text('Add Party');});
 $('#importForm').on('submit',function(e){e.preventDefault();$.ajax({url:b+'parties/import-preview',method:'POST',data:new FormData(this),processData:false,contentType:false}).done(r=>{if(!r.ok){msg(r.message,'danger');return;}validRows=r.data.rows||[];const errors=r.data.errors||[];$('#summary').text('Rows: '+r.data.rows_total+' | Valid: '+r.data.rows_ok+' | Errors: '+r.data.rows_error);const x=$('#previewRows').empty();validRows.forEach(a=>x.append('<tr><td>Valid</td><td>'+esc(a.code)+'</td><td>'+esc(a.name)+'</td><td>'+esc(a.party_type)+'</td><td class="text-success">Ready</td></tr>'));errors.forEach(a=>x.append('<tr><td>'+a.row+'</td><td>'+esc(a.data.code||'')+'</td><td>'+esc(a.data.name||'')+'</td><td>'+esc(a.data.party_type||'')+'</td><td class="text-danger">'+esc(a.message)+'</td></tr>'));$('#preview').removeClass('d-none');$('#commit').prop('disabled',!validRows.length||!!errors.length);});});
 $('#commit').click(function(){if(!validRows.length||!confirm('Commit valid party rows?'))return;$.post(b+'parties/import-commit',{type:'parties',rows_json:JSON.stringify(validRows)}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){validRows=[];$('#preview').addClass('d-none');load();}});});
 load();
});
</script>