<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3">Cylinder Groups</h1><p class="text-secondary">Cylinder types, capacities and cylinder prices.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#groupModal">Add Group</button></div>
<div class="card shadow-sm"><div class="card-body"><input id="search" class="form-control mb-3" placeholder="Search code or name"><div class="table-responsive"><table class="table"><thead><tr><th>Code</th><th>Name</th><th>Capacity</th><th>Cylinder Price</th><th>Status</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="groupModal"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5>Add Cylinder Group</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select name="code_mode" id="mode" class="form-select mb-2"><option value="AUTO">AUTO code</option><option value="MANUAL">MANUAL code</option></select><input name="code" id="code" class="form-control mb-2" placeholder="Code (manual mode)"><input name="name" class="form-control mb-2" placeholder="Name" required><input name="capacity_kg" class="form-control mb-2" inputmode="decimal" placeholder="Capacity kg" required><input name="cylinder_price" class="form-control" inputmode="decimal" value="0.00" placeholder="Cylinder price" required></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'),JSON_THROW_ON_ERROR)?>;function load(){$.getJSON(b+'cylinder-groups/data',{search:$('#search').val()}).done(r=>{let x=$('#rows').empty();(r.data.rows||[]).forEach(v=>x.append('<tr><td>'+ $('<span>').text(v.code).html()+'</td><td>'+ $('<span>').text(v.name).html()+'</td><td>'+Number(v.capacity_kg).toFixed(3)+'</td><td>'+Number(v.cylinder_price).toFixed(2)+'</td><td>'+ (v.active?'Active':'Inactive')+'</td><td>'+(v.active?'<button class="btn btn-sm btn-outline-danger del" data-id="'+v.id+'" data-code="'+$('<span>').text(v.code).html()+'">Delete</button>':'')+'</td></tr>'))}).fail(x=>alert(x.responseJSON?.message||'Load failed'))}
$('#mode').change(function(){$('#code').prop('disabled',this.value==='AUTO').val(this.value==='AUTO'?'':$('#code').val())});
$('#form').submit(function(e){e.preventDefault();$.post(b+'cylinder-groups',$(this).serialize()).done(r=>{if(r.ok)location.reload();else alert(r.message)}).fail(x=>alert(x.responseJSON?.message||'Save failed'))});
$(document).on('click','.del',function(){if(!confirm('Delete '+$(this).data('code')+'?'))return;$.post(b+'cylinder-groups/'+$(this).data('id')+'/delete',{}).done(r=>{alert(r.message);load()}).fail(x=>alert(x.responseJSON?.message||'Delete failed'))});
$('#search').keyup(load);load();});
</script>