<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-3"><div><h1 class="h3 mb-1">Cylinder Groups</h1><p class="text-secondary mb-0">Cylinder types, capacity and cylinder sale price.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#groupModal">Add Group</button></div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm"><div class="card-body"><input id="search" class="form-control mb-3" placeholder="Search code or name"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Code</th><th>Name</th><th>Capacity</th><th>Cylinder Price</th><th>Status</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="groupModal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5 id="title">Add Cylinder Group</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input type="hidden" name="id" id="id"><input type="hidden" name="active" id="active" value="1"><div id="codeWrap"><select name="code_mode" id="codeMode" class="form-select mb-2"><option>AUTO</option><option>MANUAL</option></select><input name="code" id="code" class="form-control mb-2" placeholder="Code (manual only)"></div><input name="name" id="name" class="form-control mb-2" placeholder="Name" required><input name="capacity_kg" id="capacity" class="form-control mb-2" inputmode="decimal" placeholder="Capacity kg" required><input name="cylinder_price" id="price" class="form-control mb-2" inputmode="decimal" value="0.00" placeholder="Cylinder price" required><textarea name="notes" id="notes" class="form-control" placeholder="Notes"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'))?>;function esc(v){return $('<div>').text(v??'').html();}function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}function load(){$.getJSON(b+'cylinder-groups/data',{search:$('#search').val(),limit:100},r=>{const x=$('#rows').empty();(r.data.rows||[]).forEach(a=>x.append('<tr><td>'+esc(a.code)+'</td><td>'+esc(a.name)+'</td><td>'+Number(a.capacity_kg).toFixed(3)+'</td><td>'+Number(a.cylinder_price).toFixed(2)+'</td><td>'+esc(a.active?'Active':'Inactive')+'</td><td><button class="btn btn-sm btn-outline-primary edit" data-id="'+a.id+'">Edit</button> <button class="btn btn-sm btn-outline-secondary deactivate" data-id="'+a.id+'">Deactivate</button> <button class="btn btn-sm btn-outline-danger delete" data-id="'+a.id+'">Delete</button></td></tr>'));});}
$('#search').on('keyup',load);$('#codeMode').on('change',function(){$('#code').prop('disabled',this.value==='AUTO');}).trigger('change');
$('#form').on('submit',function(e){e.preventDefault();const id=$('#id').val();const payload=$(this).serialize();$.post(id?b+'cylinder-groups/update':b+'cylinder-groups',payload).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){bootstrap.Modal.getInstance(document.getElementById('groupModal')).hide();load();}}).fail(x=>msg(x.responseJSON?.message||'Save failed','danger'));});
$('#rows').on('click','.edit',function(){const id=$(this).data('id');$.getJSON(b+'cylinder-groups/data',{search:''},r=>{const a=(r.data.rows||[]).find(x=>Number(x.id)===Number(id));if(!a)return;$('#title').text('Edit Cylinder Group');$('#id').val(a.id);$('#code').val(a.code).prop('disabled',true);$('#codeMode').hide();$('#name').val(a.name);$('#capacity').val(a.capacity_kg);$('#price').val(a.cylinder_price);$('#notes').val(a.notes||'');new bootstrap.Modal(document.getElementById('groupModal')).show();});});
$('#rows').on('click','.deactivate',function(){if(!confirm('Deactivate this group?'))return;$.post(b+'cylinder-groups/deactivate',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#rows').on('click','.delete',function(){if(!confirm('Delete this group? Deletion is allowed only when unused.'))return;$.post(b+'cylinder-groups/delete',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#groupModal').on('hidden.bs.modal',function(){$('#form')[0].reset();$('#id').val('');$('#code').prop('disabled',false);$('#codeMode').show().val('AUTO').trigger('change');$('#title').text('Add Cylinder Group');});
load();});
</script>