<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="h3">Users & Roles</h1></div>
<div id="msg" class="alert d-none"></div>
<div class="row g-3"><div class="col-lg-5"><div class="card shadow-sm"><div class="card-header">Create User</div><div class="card-body"><form id="userForm"><input name="username" class="form-control mb-2" placeholder="Username" required><input name="full_name" class="form-control mb-2" placeholder="Full name" required><input name="password" type="password" class="form-control mb-2" placeholder="Temporary password (8+ chars)" required><select name="role_id" class="form-select mb-2"><?php foreach($roles as $r):?><option value="<?=e($r['id'])?>"><?=e($r['name'])?></option><?php endforeach;?></select><select name="default_counter_id" class="form-select mb-2"><option value="0">No default counter</option><?php foreach($counters as $c):?><option value="<?=e($c['id'])?>"><?=e($c['name'])?></option><?php endforeach;?></select><button class="btn btn-primary">Create</button></form></div></div></div>
<div class="col-lg-7"><div class="card shadow-sm"><div class="card-header">Users</div><div class="card-body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Username</th><th>Name</th><th>Role</th><th>Counter</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td><?=e($u['username'])?></td><td><?=e($u['full_name'])?></td><td><?=e($u['role_name'])?></td><td><?=e($u['counter_name']??'')?></td><td><?=e($u['active']?'Active':'Inactive')?></td><td><?php if($u['active']):?><button class="btn btn-sm btn-outline-danger deactivate" data-id="<?=e($u['id'])?>">Deactivate</button><?php else:?><button class="btn btn-sm btn-outline-success activate" data-id="<?=e($u['id'])?>">Activate</button><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div></div></div></div>
<div class="card shadow-sm mt-3"><div class="card-header">Role Permission Matrix</div><div class="card-body"><?php foreach($roles as $role):?><form class="roleForm border rounded p-3 mb-2" data-role="<?=e($role['id'])?>"><h6><?=e($role['name'])?></h6><div class="row"><?php foreach($permissions as $p):?><div class="col-md-4"><label class="form-check"><input class="form-check-input" type="checkbox" name="permission_ids[]" value="<?=e($p['id'])?>" data-permission="<?=e($p['id'])?>"> <span class="form-check-label"><?=e($p['module'].' / '.$p['code'])?></span></label></div><?php endforeach;?></div><?php if($role['code']!=='ADMIN'):?><button class="btn btn-sm btn-primary mt-2">Save Permissions</button><?php endif;?></form><?php endforeach;?></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'))?>;function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}$('#userForm').on('submit',function(e){e.preventDefault();$.post(b+'users',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)location.reload();});});$('.roleForm').each(function(){const f=$(this),id=f.data('role');$.getJSON(b+'users/role-permissions',{role_id:id},r=>(r.data||[]).forEach(id=>f.find('[data-permission="'+id+'"]').prop('checked',true)));});$('.roleForm').on('submit',function(e){e.preventDefault();const f=$(this),data=f.serializeArray();data.push({name:'role_id',value:f.data('role')});$.post(b+'users/permissions',data).done(r=>msg(r.message,r.ok?'success':'danger'));});});
</script><script>
$(function(){
const b=<?=json_encode(url('/'))?>;
$('#userForm').on('submit',function(e){e.preventDefault();$.post(b+'users',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)location.reload();});});
$('.deactivate').click(function(){if(!confirm('Deactivate user?'))return;$.post(b+'users/deactivate',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)location.reload();});});
$('.activate').click(function(){if(!confirm('Activate user?'))return;$.post(b+'users/activate',{id:$(this).data('id')}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)location.reload();});});
});
</script>