<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3">Purchases</h1><p class="text-secondary mb-0">Gas refills and new cylinders purchased from suppliers.</p></div></div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm mb-3"><div class="card-body">
<form id="form">
<div class="row g-2">
<div class="col-md-2"><label class="form-label">Date</label><input name="purchase_date" id="date" type="date" class="form-control" value="<?=e($today)?>"></div>
<div class="col-md-4"><label class="form-label">Supplier</label><input id="supplierSearch" class="form-control" placeholder="Search supplier"><select id="supplier" name="supplier_id" class="form-select mt-1" required></select></div>
<div class="col-md-3"><label class="form-label">Supplier Invoice No.</label><input name="supplier_invoice_no" class="form-control"></div>
<div class="col-md-3"><label class="form-label">Paid Now</label><input name="paid_amount" id="paid" class="form-control" inputmode="decimal" value="0.00"></div>
<div class="col-md-2"><label class="form-label">Method</label><select name="method" id="method" class="form-select"><option>CASH</option><option>ONLINE</option><option>CHEQUE</option></select></div>
<div class="col-md-2"><label class="form-label">Counter ID</label><input name="counter_id" class="form-control"></div>
<div class="col-md-8"><input name="notes" class="form-control" placeholder="Notes"></div>
<div class="col-12 cheque d-none"><div class="row g-2"><div class="col-md-4"><input name="cheque_no" class="form-control" placeholder="Cheque no."></div><div class="col-md-4"><input name="cheque_bank" class="form-control" placeholder="Bank"></div><div class="col-md-4"><input name="cheque_date" type="date" class="form-control" value="<?=e($today)?>"></div></div></div>
</div>
<hr>
<div class="d-flex flex-wrap gap-2 mb-2"><strong>Add line</strong><button type="button" id="addFill" class="btn btn-sm btn-outline-primary">Gas Refill</button><button type="button" id="addNew" class="btn btn-sm btn-outline-primary">New Cylinders</button></div>
<div id="lineEditor"></div>
<div class="table-responsive mt-3"><table class="table table-sm"><thead><tr><th>Type</th><th>Description</th><th>Qty/Gas</th><th>Rate</th><th>Cost</th><th>Amount</th><th></th></tr></thead><tbody id="lines"></tbody></table></div>
<input type="hidden" name="lines_json" id="linesJson">
<div class="d-flex justify-content-between align-items-center"><strong>Total <span id="total">0.00</span></strong><button class="btn btn-primary">Post Purchase</button></div>
</form></div></div>
<div class="card shadow-sm"><div class="card-header">Purchase History</div><div class="card-body"><div class="row g-2 mb-3"><div class="col-md-3"><input id="from" type="date" class="form-control" value="<?=e($today)?>"></div><div class="col-md-3"><input id="to" type="date" class="form-control" value="<?=e($today)?>"></div><div class="col-md-3"><input id="filter" class="form-control" placeholder="Search"></div><div class="col-md-3"><select id="status" class="form-select"><option value="">All status</option><option>POSTED</option><option>VOID</option></select></div></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Doc</th><th>Date</th><th>Supplier</th><th>Total</th><th>Paid</th><th>Status</th><th></th></tr></thead><tbody id="history"></tbody></table></div></div></div>
<script>
$(function(){
const b=<?=json_encode(url('/'))?>;const lines=[];
function esc(v){return $('<div>').text(v??'').html();}function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}
function recalc(){let t=0;lines.forEach(l=>{if(l.line_type==='GAS_FILL')t+=Number(l.gas_kg)*Number(l.gas_rate);else t+=(Number(l.quantity)*Number(l.cylinder_cost))+(Number(l.quantity)*Number(l.initial_gas_kg)*Number(l.gas_rate));});$('#total').text(t.toFixed(2));$('#linesJson').val(JSON.stringify(lines));}
function loadGroups(cb){$.getJSON(b+'purchases/groups',r=>cb(r.data||[]));}
function loadCylinders(cb){$.getJSON(b+'purchases/cylinders',{},r=>cb(r.data||[]));}
$('#supplierSearch').on('input',function(){const q=this.value;if(q.length<2)return;$.getJSON(b+'purchases/suppliers',{q},r=>{$('#supplier').empty();(r.data||[]).forEach(x=>$('#supplier').append(new Option(x.code+' - '+x.name,x.id)));});});
$('#method').on('change',()=>$('.cheque').toggleClass('d-none',$('#method').val()!=='CHEQUE'));
$('#addFill').click(()=>loadCylinders(rows=>{let opts=rows.map(x=>'<option value="'+x.id+'">'+esc(x.code)+' - '+esc(x.group_name)+' ('+esc(x.gas_kg)+'/'+esc(x.capacity_kg)+')</option>').join('');$('#lineEditor').html('<div class="border rounded p-3"><div class="row g-2"><div class="col-md-5"><select id="fillCylinder" class="form-select">'+opts+'</select></div><div class="col-md-2"><input id="fillGas" class="form-control" placeholder="Gas added kg" inputmode="decimal"></div><div class="col-md-2"><input id="fillRate" class="form-control" placeholder="Rate / kg" inputmode="decimal"></div><div class="col-md-3"><button type="button" id="addFillLine" class="btn btn-success w-100">Add</button></div></div></div>');});
$('#addNew').click(()=>loadGroups(groups=>{let opts=groups.map(x=>'<option value="'+x.id+'">'+esc(x.code)+' - '+esc(x.name)+' ('+esc(x.capacity_kg)+'kg)</option>').join('');$('#lineEditor').html('<div class="border rounded p-3"><div class="row g-2"><div class="col-md-3"><select id="newGroup" class="form-select">'+opts+'</select></div><div class="col-md-2"><input id="newQty" type="number" min="1" class="form-control" placeholder="Qty" value="1"></div><div class="col-md-2"><input id="newGas" class="form-control" placeholder="Initial gas" value="0"></div><div class="col-md-2"><input id="newCost" class="form-control" placeholder="Cylinder cost"></div><div class="col-md-2"><input id="newRate" class="form-control" placeholder="Gas rate"></div><div class="col-md-1"><select id="newMode" class="form-select"><option>AUTO</option><option>MANUAL</option></select></div><div class="col-md-8"><textarea id="newCodes" class="form-control" placeholder="Manual codes separated by comma/space"></textarea></div><div class="col-md-2"><select id="newCondition" class="form-select"><option>GOOD</option><option>DAMAGED</option></select></div><div class="col-md-2"><button type="button" id="addNewLine" class="btn btn-success w-100">Add</button></div></div></div>');});
$('#lineEditor').on('click','#addFillLine',function(){const id=Number($('#fillCylinder').val());const opt=$('#fillCylinder option:selected').text();lines.push({line_type:'GAS_FILL',cylinder_id:id,gas_kg:$('#fillGas').val(),gas_rate:$('#fillRate').val()});render(opt);});
$('#lineEditor').on('click','#addNewLine',function(){lines.push({line_type:'NEW_CYLINDERS',group_id:Number($('#newGroup').val()),quantity:Number($('#newQty').val()),initial_gas_kg:$('#newGas').val(),cylinder_cost:$('#newCost').val(),gas_rate:$('#newRate').val(),code_mode:$('#newMode').val(),codes:($('#newCodes').val()||'').split(/[s,]+/).filter(Boolean),condition_code:$('#newCondition').val()});render('New '+$('#newGroup option:selected').text());});
function render(label){$('#lines').empty();lines.forEach((l,i)=>{let qty=l.line_type==='GAS_FILL'?l.gas_kg:l.quantity;let rate=l.gas_rate;let amount=l.line_type==='GAS_FILL'?Number(l.gas_kg)*Number(l.gas_rate):(Number(l.quantity)*Number(l.cylinder_cost))+(Number(l.quantity)*Number(l.initial_gas_kg)*Number(l.gas_rate));$('#lines').append('<tr><td>'+esc(l.line_type)+'</td><td>'+esc(l.cylinder_id||label||l.group_id)+'</td><td>'+esc(qty)+'</td><td>'+esc(rate)+'</td><td>'+esc(l.cylinder_cost||'0.00')+'</td><td>'+amount.toFixed(2)+'</td><td><button type="button" class="btn btn-sm btn-outline-danger remove" data-i="'+i+'">Remove</button></td></tr>');});recalc();}
$('#lines').on('click','.remove',function(){lines.splice(Number($(this).data('i')),1);render('');});
$('#form').on('submit',function(e){e.preventDefault();if(!lines.length){msg('Add at least one purchase line.','danger');return;}$('#linesJson').val(JSON.stringify(lines));$.post(b+'purchases',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){lines.splice(0);render('');load();}}).fail(x=>msg(x.responseJSON?.message||'Purchase failed.','danger'));});
function load(){let q={from:$('#from').val(),to:$('#to').val(),status:$('#status').val(),search:$('#filter').val()};$.getJSON(b+'purchases/data',q,r=>{let x=$('#history').empty();(r.data.rows||[]).forEach(a=>x.append('<tr><td>'+esc(a.doc_no)+'</td><td>'+esc(a.purchase_date)+'</td><td>'+esc(a.supplier_name)+'</td><td>'+Number(a.total).toFixed(2)+'</td><td>'+Number(a.paid_amount).toFixed(2)+'</td><td>'+esc(a.status)+'</td><td>'+(a.status==='POSTED'?'<button class="btn btn-sm btn-outline-danger void" data-id="'+a.id+'">Void</button>':'')+'</td></tr>'));});}
$('#history').on('click','.void',function(){let reason=prompt('Void reason');if(!reason)return;$.post(b+'purchases/void',{id:$(this).data('id'),reason}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});
$('#from,#to,#status,#filter').on('change keyup',load);load();recalc();
});
</script>