<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Purchases</h1><p class="text-secondary mb-0">Gas refills and new-cylinder purchases.</p></div></div>
<div class="card shadow-sm mb-3"><div class="card-body"><form id="pform">
<div class="row g-2"><div class="col-md-3"><label class="form-label">Date</label><input name="purchase_date" type="date" class="form-control" value="<?=e(date('Y-m-d'))?>"></div><div class="col-md-5"><label class="form-label">Supplier</label><select name="supplier_id" class="form-select"><?php foreach($suppliers as $s):?><option value="<?=e($s['id'])?>"><?=e($s['code'].' - '.$s['name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Invoice</label><input name="supplier_invoice_no" class="form-control"></div></div>
<hr><div class="d-flex gap-2 mb-2"><button type="button" id="addFill" class="btn btn-outline-primary">Add Gas Refill</button><button type="button" id="addNew" class="btn btn-outline-secondary">Add New Cylinders</button></div>
<div id="lines"></div><div class="row g-2 mt-2"><div class="col-md-3"><label class="form-label">Paid now</label><input name="paid_amount" id="paid" class="form-control" value="0.00"></div><div class="col-md-3"><label class="form-label">Method</label><select name="method" id="method" class="form-select"><option>CASH</option><option>ONLINE</option><option>CHEQUE</option></select></div><div class="col-md-3"><label class="form-label">Counter</label><input name="counter_id" class="form-control" value="<?=e((string)($user['default_counter_id']??''))?>"></div><div class="col-md-3"><label class="form-label">Notes</label><input name="notes" class="form-control"></div></div>
<div id="cheque" class="row g-2 mt-2 d-none"><div class="col-md-4"><input name="cheque[cheque_no]" class="form-control" placeholder="Cheque no"></div><div class="col-md-4"><input name="cheque[bank]" class="form-control" placeholder="Bank"></div><div class="col-md-4"><input name="cheque[cheque_date]" type="date" class="form-control"></div></div>
<div class="text-end mt-3"><strong>Total: <span id="total">0.00</span></strong> <button class="btn btn-primary ms-3">Post Purchase</button></div></form><div id="msg" class="mt-3"></div></div></div>
<div class="card shadow-sm"><div class="card-header"><strong>Purchase History</strong></div><div class="card-body"><div class="table-responsive"><table class="table table-sm" id="pt"><thead><tr><th>Doc</th><th>Date</th><th>Supplier</th><th>Total</th><th>Paid</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody></tbody></table></div></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'),JSON_THROW_ON_ERROR)?>;let lines=[];
const groups=<?=json_encode($groups,JSON_THROW_ON_ERROR)?>, cylinders=<?=json_encode($cylinders,JSON_THROW_ON_ERROR)?>;
function esc(v){return $('<div>').text(v??'').html();}
function render(){let h='';lines.forEach((l,i)=>{if(l.line_type==='GAS_FILL'){h+='<div class="border rounded p-2 mb-2"><strong>Gas Refill</strong><div class="row g-2 mt-1"><div class="col-md-4"><select class="form-select fill-cylinder" data-i="'+i+'">'+cylinders.map(c=>'<option value="'+c.id+'" '+(c.id==l.cylinder_id?'selected':'')+'>'+esc(c.code)+' (gas '+esc(c.gas_kg)+' / '+esc(c.capacity_kg)+')</option>').join('')+'</select></div><div class="col-md-3"><input class="form-control fill-gas" data-i="'+i+'" value="'+esc(l.gas_kg)+'" placeholder="Gas kg"></div><div class="col-md-3"><input class="form-control fill-rate" data-i="'+i+'" value="'+esc(l.gas_rate)+'" placeholder="Rate/kg"></div><div class="col-md-2"><button type="button" class="btn btn-outline-danger remove" data-i="'+i+'">Remove</button></div></div></div>'}
else{h+='<div class="border rounded p-2 mb-2"><strong>New Cylinders</strong><div class="row g-2 mt-1"><div class="col-md-3"><select class="form-select new-group" data-i="'+i+'">'+groups.map(g=>'<option value="'+g.id+'" '+(g.id==l.group_id?'selected':'')+'>'+esc(g.code)+' - '+esc(g.name)+'</option>').join('')+'</select></div><div class="col-md-2"><input class="form-control new-qty" data-i="'+i+'" value="'+l.quantity+'"></div><div class="col-md-2"><input class="form-control new-gas" data-i="'+i+'" value="'+esc(l.gas_kg)+'" placeholder="Initial gas"></div><div class="col-md-2"><input class="form-control new-cost" data-i="'+i+'" value="'+esc(l.cylinder_cost)+'" placeholder="Cyl cost"></div><div class="col-md-2"><input class="form-control new-rate" data-i="'+i+'" value="'+esc(l.gas_rate)+'" placeholder="Gas rate"></div><div class="col-md-1"><button type="button" class="btn btn-outline-danger remove" data-i="'+i+'">×</button></div><div class="col-12"><select class="form-select new-condition" data-i="'+i+'"><option>GOOD</option><option>DAMAGED</option></select></div><div class="col-12"><input class="form-control new-codes" data-i="'+i+'" placeholder="Manual codes comma-separated (AUTO can stay blank)"></div></div></div>'}});$('#lines').html(h);calc();}
function calc(){let t=0;lines.forEach(l=>{if(l.line_type==='GAS_FILL')t+=Number(l.gas_kg||0)*Number(l.gas_rate||0);else t+=Number(l.quantity||0)*(Number(l.cylinder_cost||0)+Number(l.gas_kg||0)*Number(l.gas_rate||0));});$('#total').text(t.toFixed(2));}
$('#addFill').click(()=>{lines.push({line_type:'GAS_FILL',cylinder_id:cylinders[0]?.id||0,gas_kg:'1.000',gas_rate:'0.00'});render()});
$('#addNew').click(()=>{lines.push({line_type:'NEW_CYLINDERS',group_id:groups[0]?.id||0,quantity:1,gas_kg:'0.000',cylinder_cost:'0.00',gas_rate:'0.00',condition_code:'GOOD',code_mode:'AUTO'});render()});
$(document).on('input change','.fill-cylinder,.fill-gas,.fill-rate,.new-group,.new-qty,.new-gas,.new-cost,.new-rate,.new-condition,.new-codes',function(){let i=Number($(this).data('i')),l=lines[i],c=$(this).attr('class');if(c.includes('fill-cylinder'))l.cylinder_id=Number(this.value);else if(c.includes('fill-gas'))l.gas_kg=this.value;else if(c.includes('fill-rate'))l.gas_rate=this.value;else if(c.includes('new-group'))l.group_id=Number(this.value);else if(c.includes('new-qty'))l.quantity=Number(this.value);else if(c.includes('new-gas'))l.gas_kg=this.value;else if(c.includes('new-cost'))l.cylinder_cost=this.value;else if(c.includes('new-rate'))l.gas_rate=this.value;else if(c.includes('new-condition'))l.condition_code=this.value;else if(c.includes('new-codes')){l.code_mode='MANUAL';l.codes=this.value.split(',').map(x=>x.trim()).filter(Boolean);}calc();});
$(document).on('click','.remove',function(){lines.splice(Number($(this).data('i')),1);render()});
$('#method').change(function(){$('#cheque').toggleClass('d-none',this.value!=='CHEQUE')});
$('#pform').submit(function(e){e.preventDefault();let o={};$(this).serializeArray().forEach(x=>{if(!x.name.startsWith('cheque['))o[x.name]=x.value});o.lines=lines;if($('#method').val()==='CHEQUE')o.cheque={cheque_no:$('[name="cheque[cheque_no]"]').val(),bank:$('[name="cheque[bank]"]').val(),cheque_date:$('[name="cheque[cheque_date]"]').val()};$.post(b+'purchases',o).done(r=>{alert(r.message);if(r.ok){lines=[];render();load();}}).fail(x=>alert(x.responseJSON?.message||'Purchase failed'))});
function load(){$.getJSON(b+'purchases/data').done(r=>{let x=$('#pt tbody').empty();(r.data.rows||[]).forEach(v=>x.append('<tr><td>'+v.doc_no+'</td><td>'+v.purchase_date+'</td><td>'+v.supplier_code+' - '+v.supplier_name+'</td><td>'+Number(v.total).toFixed(2)+'</td><td>'+Number(v.paid_amount).toFixed(2)+'</td><td>'+Number(v.balance_after).toFixed(2)+'</td><td>'+v.status+'</td><td>'+(v.status==='POSTED'?'<button class="btn btn-sm btn-outline-danger pv" data-id="'+v.id+'">Void</button>':'')+'</td></tr>'));});}
$(document).on('click','.pv',function(){let reason=prompt('Void reason:');if(!reason)return;$.post(b+'purchases/'+$(this).data('id')+'/void',{reason}).done(r=>{alert(r.message);load()}).fail(x=>alert(x.responseJSON?.message||'Void failed'))});render();load();});
</script>