<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3">Cash Counter</h1><p class="text-secondary mb-0">Open/close sessions, manual cash entries and counter transfers.</p></div></div>
<div id="msg" class="alert d-none"></div>
<div class="row g-3">
<div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Session</div><div class="card-body"><div class="row g-2"><div class="col-md-5"><label class="form-label">Counter</label><select id="counter" class="form-select"><?php foreach($counters as $c):?><option value="<?=e($c['id'])?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><label class="form-label">Opening cash</label><input id="opening" class="form-control" inputmode="decimal" value="0.00"></div><div class="col-md-3 d-flex align-items-end"><button id="open" class="btn btn-primary w-100">Open</button></div></div><hr><div class="row g-2"><div class="col-md-4"><label class="form-label">Counted cash</label><input id="counted" class="form-control" inputmode="decimal" value="0.00"></div><div class="col-md-3 d-flex align-items-end"><button id="close" class="btn btn-danger w-100">Close</button></div><div class="col-md-5"><div id="status" class="alert alert-secondary mb-0">Checking...</div></div></div></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Manual Cash In / Out</div><div class="card-body"><form id="manual"><div class="row g-2"><div class="col-md-3"><select name="direction" class="form-select"><option>IN</option><option>OUT</option></select></div><div class="col-md-4"><input name="amount" class="form-control" placeholder="Amount" inputmode="decimal"></div><div class="col-md-5"><input name="reason" class="form-control" placeholder="Reason"></div><div class="col-12"><button class="btn btn-outline-primary">Post Adjustment</button></div></div></form></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm"><div class="card-header">Transfer Between Counters</div><div class="card-body"><form id="transfer"><div class="row g-2"><div class="col-md-6"><select name="from_counter_id" class="form-select"><?php foreach($counters as $c):?><option value="<?=e($c['id'])?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-6"><select name="to_counter_id" class="form-select"><?php foreach($counters as $c):?><option value="<?=e($c['id'])?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="col-md-4"><input name="amount" class="form-control" inputmode="decimal" placeholder="Amount"></div><div class="col-md-4"><input name="transfer_date" type="date" class="form-control" value="<?=e(date('Y-m-d'))?>"></div><div class="col-md-4"><button class="btn btn-outline-primary w-100">Transfer</button></div><div class="col-12"><input name="notes" class="form-control" placeholder="Notes"></div></div></form></div></div></div>
</div>
<script>
$(function(){const b=<?=json_encode(url('/'))?>;function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}function status(){ $.getJSON(b+'counter/status',{counter_id:$('#counter').val()},r=>{if(r.data){$('#status').text('Open since '+r.data.opened_at);}else $('#status').text('No open session.');});}$('#counter').on('change',status);$('#open').click(()=>$.post(b+'counter/open',{counter_id:$('#counter').val(),opening_cash:$('#opening').val()}).done(r=>{msg(r.message,r.ok?'success':'danger');status();}));$('#close').click(()=>$.post(b+'counter/close',{counter_id:$('#counter').val(),counted_cash:$('#counted').val()}).done(r=>{msg(r.message+(r.data?' Expected '+r.data.expected+', variance '+r.data.variance:''),r.ok?'success':'danger');status();}));$('#manual').on('submit',function(e){e.preventDefault();const d=Object.fromEntries(new FormData(this));d.counter_id=$('#counter').val();$.post(b+'counter/manual',d).done(r=>msg(r.message,r.ok?'success':'danger'));});$('#transfer').on('submit',function(e){e.preventDefault();$.post(b+'counter/transfer',$(this).serialize()).done(r=>msg(r.message,r.ok?'success':'danger'));});status();});
</script>