<div class="d-flex flex-wrap align-items-center justify-content-between gap-3 mb-4">
<div><h1 class="h3 mb-1">Settings</h1><p class="text-secondary mb-0">Shop configuration, POS behavior, code generation and document settings.</p></div>
<?php if ($GLOBALS['auth']->can('users.view')): ?><a class="btn btn-outline-secondary" href="<?=e(url('/users'))?>">Users & Roles</a><?php endif; ?>
</div>
<?php $sales=$settings['sales']??[];$salesCredit=$settings['sales_credit']??[];$tax=$settings['tax']??[];$printing=$settings['printing']??[];$cheques=$settings['cheques']??[];$code=$settings['code_generation']??[];$general=$settings['general']??[]; ?>
<?php if($GLOBALS['auth']->can('settings.manage')): ?>
<div class="row g-3">
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>POS Transaction Types</strong></div><div class="card-body">
<form method="post" action="<?=e(url('/settings/pos'))?>"><?=csrf_input()?>
<label class="form-label">Visible transaction types</label>
<div class="form-check"><input class="form-check-input" type="checkbox" name="transaction_types[]" value="GAS_SALE" id="gasType" <?=in_array('GAS_SALE',explode(',',($sales['pos_transaction_types']??'')),true)?'checked':''?>><label class="form-check-label" for="gasType">Gas Sale</label></div>
<div class="form-check"><input class="form-check-input" type="checkbox" name="transaction_types[]" value="EMPTY_CYLINDER_SALE" id="emptyType" <?=in_array('EMPTY_CYLINDER_SALE',explode(',',($sales['pos_transaction_types']??'')),true)?'checked':''?>><label class="form-check-label" for="emptyType">Empty Cylinder Sale</label></div>
<label class="form-label mt-3">Default POS transaction type</label><select name="default_transaction_type" class="form-select"><option value="GAS_SALE" <?=($sales['pos_default_transaction_type']??'GAS_SALE')==='GAS_SALE'?'selected':''?>>Gas Sale</option><option value="EMPTY_CYLINDER_SALE" <?=($sales['pos_default_transaction_type']??'')==='EMPTY_CYLINDER_SALE'?'selected':''?>>Empty Cylinder Sale</option></select>
<button class="btn btn-primary mt-3">Save POS Settings</button></form>
</div></div></div>
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>Sales & Credit</strong></div><div class="card-body"><form method="post" action="<?=e(url('/settings/group'))?>"><?=csrf_input()?><input type="hidden" name="setting_group" value="sales_credit">
<div class="row g-2">
<div class="col-md-6"><label class="form-label">Credit enforcement</label><select name="credit_limit_enforcement" class="form-select"><option value="BLOCK" <?=strtoupper($salesCredit['credit_limit_enforcement']??'BLOCK')==='BLOCK'?'selected':''?>>Block</option><option value="WARN" <?=strtoupper($salesCredit['credit_limit_enforcement']??'')==='WARN'?'selected':''?>>Warn</option></select></div>
<div class="col-md-6"><label class="form-label">Default payment</label><select name="default_payment_method" class="form-select"><option>CASH</option><option <?=($salesCredit['default_payment_method']??'')==='ONLINE'?'selected':''?>>ONLINE</option><option <?=($salesCredit['default_payment_method']??'')==='CHEQUE'?'selected':''?>>CHEQUE</option></select></div>
<div class="col-md-4"><label class="form-label">Allow rate edit</label><select name="allow_rate_edit" class="form-select"><option value="1" <?=($salesCredit['allow_rate_edit']??'1')==='1'?'selected':''?>>Yes</option><option value="0" <?=($salesCredit['allow_rate_edit']??'')==='0'?'selected':''?>>No</option></select></div>
<div class="col-md-4"><label class="form-label">Allow advance</label><select name="allow_advance" class="form-select"><option value="1" <?=($salesCredit['allow_advance']??'1')==='1'?'selected':''?>>Yes</option><option value="0" <?=($salesCredit['allow_advance']??'')==='0'?'selected':''?>>No</option></select></div>
<div class="col-md-2"><label class="form-label">Gas decimals</label><input name="gas_decimals" class="form-control" value="<?=e($salesCredit['gas_decimals']??'3')?>"></div>
<div class="col-md-2"><label class="form-label">Money decimals</label><input name="money_decimals" class="form-control" value="<?=e($salesCredit['money_decimals']??'2')?>"></div>
</div><button class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>Tax</strong></div><div class="card-body"><form method="post" action="<?=e(url('/settings/group'))?>"><?=csrf_input()?><input type="hidden" name="setting_group" value="tax"><div class="row g-2"><div class="col-md-4"><label class="form-label">Enabled</label><select name="enabled" class="form-select"><option value="0" <?=($tax['enabled']??'0')==='0'?'selected':''?>>No</option><option value="1" <?=($tax['enabled']??'')==='1'?'selected':''?>>Yes</option></select></div><div class="col-md-4"><label class="form-label">Name</label><input name="tax_name" class="form-control" value="<?=e($tax['tax_name']??'Tax')?>"></div><div class="col-md-4"><label class="form-label">Percent</label><input name="rate_percent" class="form-control" inputmode="decimal" value="<?=e($tax['rate_percent']??'0.00')?>"></div><div class="col-md-4"><label class="form-label">Applies to gas</label><select name="applies_to_gas" class="form-select"><option value="1" <?=($tax['applies_to_gas']??'1')==='1'?'selected':''?>>Yes</option><option value="0" <?=($tax['applies_to_gas']??'')==='0'?'selected':''?>>No</option></select></div></div><button class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>Code Generation</strong></div><div class="card-body"><form method="post" action="<?=e(url('/settings/group'))?>"><?=csrf_input()?><input type="hidden" name="setting_group" value="code_generation"><div class="row g-2">
<div class="col-md-4"><label class="form-label">Cylinder mode</label><select name="cylinder_code_mode" class="form-select"><option>AUTO</option><option <?=($code['cylinder_code_mode']??'')==='MANUAL'?'selected':''?>>MANUAL</option></select></div>
<div class="col-md-8"><label class="form-label">Cylinder pattern</label><input name="cylinder_code_pattern" class="form-control" value="<?=e($code['cylinder_code_pattern']??'{GROUP}{CAP}-{SEQ:6}')?>"><div class="form-text">{GROUP}, {CAP}, {SEQ} supported.</div></div>
<div class="col-md-3"><label class="form-label">Cylinder seq width</label><input name="cylinder_seq_width" class="form-control" value="<?=e($code['cylinder_seq_width']??'6')?>"></div>
<div class="col-md-4"><label class="form-label">Group mode</label><select name="group_code_mode" class="form-select"><option>AUTO</option><option <?=($code['group_code_mode']??'')==='MANUAL'?'selected':''?>>MANUAL</option></select></div>
<div class="col-md-3"><label class="form-label">Group prefix</label><input name="group_code_prefix" class="form-control" value="<?=e($code['group_code_prefix']??'G')?>"></div>
<div class="col-md-2"><label class="form-label">Group width</label><input name="group_code_width" class="form-control" value="<?=e($code['group_code_width']??'3')?>"></div>
</div><button class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>Cheque Posting</strong></div><div class="card-body"><form method="post" action="<?=e(url('/settings/group'))?>"><?=csrf_input()?><input type="hidden" name="setting_group" value="cheques"><label class="form-label">Ledger posting</label><select name="cheque_ledger_posting" class="form-select"><option value="ON_CLEARANCE" <?=strtoupper($cheques['cheque_ledger_posting']??$cheques['posting_mode']??'ON_CLEARANCE')==='ON_CLEARANCE'?'selected':''?>>On clearance</option><option value="ON_RECEIPT" <?=strtoupper($cheques['cheque_ledger_posting']??'')==='ON_RECEIPT'?'selected':''?>>On receipt</option></select><button class="btn btn-primary mt-3">Save</button></form></div></div></div>
<div class="col-lg-6"><div class="card shadow-sm h-100"><div class="card-header"><strong>Printing</strong></div><div class="card-body"><form method="post" action="<?=e(url('/settings/group'))?>"><?=csrf_input()?><input type="hidden" name="setting_group" value="printing"><div class="row g-2"><div class="col-md-5"><label class="form-label">Paper size</label><select name="paper_size" class="form-select"><option value="80MM" <?=($printing['paper_size']??'80MM')==='80MM'?'selected':''?>>80 mm Thermal</option><option value="A4" <?=($printing['paper_size']??'')==='A4'?'selected':''?>>A4</option></select></div><div class="col-md-7"><label class="form-label">Header</label><input name="header_text" class="form-control" value="<?=e($printing['header_text']??'')?>"></div><div class="col-12"><label class="form-label">Footer</label><input name="footer_text" class="form-control" value="<?=e($printing['footer_text']??'')?>"></div></div><button class="btn btn-primary mt-3">Save</button></form></div></div></div>
</div>
<?php endif; ?>
<div class="card shadow-sm mt-4"><div class="card-header"><strong>Current Settings</strong></div><div class="card-body"><div class="row g-3"><?php foreach($settings as $groupName=>$groupValues):?><div class="col-12"><h6 class="text-uppercase text-secondary"><?=e($groupName)?></h6><div class="table-responsive"><table class="table table-sm"><tbody><?php foreach($groupValues as $key=>$value):?><tr><td><?=e($key)?></td><td><?=e($value)?></td></tr><?php endforeach;?></tbody></table></div></div><?php endforeach;?></div></div></div>
