<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3">Point of Sale</h1><p class="text-secondary mb-0">Issue gas or sell cylinders with one atomic transaction.</p></div></div>
<div class="card shadow-sm mb-3"><div class="card-body"><div class="row g-2">
<div class="col-md-3"><label class="form-label">Transaction Type</label><select id="transactionType" class="form-select"></select></div>
<div class="col-md-4"><label class="form-label">Customer</label><input id="customerSearch" class="form-control" placeholder="Search customer code, name or phone"><select id="customer" class="form-select mt-1"></select></div>
<div class="col-md-2"><label class="form-label">Date</label><input id="txnDate" type="date" class="form-control"></div>
<div class="col-md-2"><label class="form-label">Payment</label><select id="method" class="form-select"><option>CASH</option><option>ONLINE</option><option>CHEQUE</option></select></div>
<div class="col-md-1"><label class="form-label">Received</label><input id="received" class="form-control" inputmode="decimal" value="0.00"></div>
</div></div></div>
<div class="card shadow-sm"><div class="card-header d-flex justify-content-between"><strong>Shop Cylinders</strong><select id="group" class="form-select form-select-sm" style="max-width:260px"><option value="0">All groups</option></select></div><div class="card-body"><div id="cylinders" class="row g-2"></div><div class="d-flex justify-content-between mt-3"><strong>Total: <span id="total">0.00</span></strong><button id="save" class="btn btn-primary">Post Sale</button></div></div></div>
<script>
$(function(){
 const base='<?=e(url('/'))?>'; $('#txnDate').val(new Date().toISOString().slice(0,10));
 function esc(x){return $('<div>').text(x??'').html();}
 function loadConfig(){return $.getJSON(base+'pos/config',function(r){let s=$('#transactionType').empty();(r.data.transaction_types||[]).forEach(t=>s.append('<option value="'+esc(t)+'">'+esc(t.replaceAll('_',' '))+'</option>'));});}
 function load(){let g=$('#group').val();$.getJSON(base+'pos/cylinders',{group_id:g},function(r){let b=$('#cylinders').empty(),groups={};r.data.forEach(x=>{groups[x.group_id]=x.group_code+' - '+x.group_name+' ('+x.capacity_kg+'kg)';b.append('<div class="col-6 col-md-3"><div class="border rounded p-2 h-100"><div class="fw-bold">'+esc(x.code)+'</div><div>'+esc(x.group_name)+'</div><div>Gas: '+esc(x.gas_kg)+' / '+esc(x.capacity_kg)+' kg</div><div class="form-check mt-2"><input class="form-check-input pick" type="checkbox" data-id="'+x.id+'"><label class="form-check-label">Select</label></div><div class="mt-2"><label class="form-label small mb-1">Gas kg</label><input class="form-control form-control-sm gas" data-id="'+x.id+'" data-code="'+esc(x.code)+'" data-max="'+x.gas_kg+'" value="'+x.gas_kg+'"></div><div class="form-check mt-2 sell-wrap"><input class="form-check-input sell" type="checkbox" data-id="'+x.id+'"><label class="form-check-label">Sell cylinder</label></div><input class="form-control form-control-sm rate mt-1" data-id="'+x.id+'" placeholder="Gas rate"><input class="form-control form-control-sm cp mt-1" data-id="'+x.id+'" placeholder="Cylinder price"></div></div>')});let s=$('#group').empty().append('<option value="0">All groups</option>');Object.entries(groups).forEach(([id,n])=>s.append('<option value="'+id+'">'+esc(n)+'</option>'));if(g)s.val(g);});}
 function refreshMode(){let empty=$('#transactionType').val()==='EMPTY_CYLINDER_SALE';$('.sell-wrap,.rate').toggle(!empty);$('.gas').prop('disabled',empty);$('.gas').each(function(){if(empty)$(this).val('0.000');});}
 $('#transactionType').on('change',refreshMode); $('#group').on('change',load);
 $('#customerSearch').on('input',function(){let q=this.value;if(q.length<2)return;$.getJSON(base+'pos/customers',{q:q},function(r){let s=$('#customer').empty();r.data.forEach(x=>s.append('<option value="'+x.id+'">'+esc(x.code+' - '+x.name)+'</option>'));});});
 $('#save').on('click',function(){let empty=$('#transactionType').val()==='EMPTY_CYLINDER_SALE',lines=[];$('.gas').each(function(){let id=$(this).data('id'),gas=$(this).val(),sell=$('.sell[data-id="'+id+'"]').is(':checked');if($('.pick[data-id="'+id+'"]').is(':checked')){lines.push({cylinder_id:id,type:empty?'SELL_EMPTY':(sell?'SELL_FILLED':'ISSUE'),gas_kg:empty?'0.000':gas,rate:$('.rate[data-id="'+id+'"]').val()||'0',cylinder_price:$('.cp[data-id="'+id+'"]').val()||'0'});}});if(!lines.length){alert('Select at least one cylinder.');return;}let hasSell=empty||lines.some(x=>x.type==='SELL_FILLED');if(hasSell&&!confirm(lines.length+' cylinder(s) will leave company stock permanently. Continue?'))return;$.post(base+'pos',{txn_date:$('#txnDate').val(),transaction_type:$('#transactionType').val(),customer_id:$('#customer').val(),method:$('#method').val(),received_amount:$('#received').val(),lines_json:JSON.stringify(lines)}).done(r=>{alert(r.message);if(r.ok)load();}).fail(x=>alert(x.responseJSON?.message||'Sale failed'));});
 loadConfig().always(function(){load();refreshMode();});
});
</script>