<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3">Payments</h1><p class="text-secondary mb-0">Supplier payments and purchase-linked payments.</p></div></div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm mb-3"><div class="card-body"><form id="form"><div class="row g-2">
<div class="col-md-2"><label class="form-label">Date</label><input name="payment_date" type="date" class="form-control" value="<?=e($today)?>"></div>
<div class="col-md-4"><label class="form-label">Supplier</label><input id="search" class="form-control" placeholder="Search supplier"><select id="party" name="party_id" class="form-select mt-1" required></select></div>
<div class="col-md-2"><label class="form-label">Amount</label><input name="amount" class="form-control" inputmode="decimal" value="0.00" required></div>
<div class="col-md-2"><label class="form-label">Method</label><select name="method" id="method" class="form-select"><option>CASH</option><option>ONLINE</option><option>CHEQUE</option></select></div>
<div class="col-md-2"><label class="form-label">Counter ID</label><input name="counter_id" class="form-control"></div>
<div class="col-12 cheque d-none"><div class="row g-2"><div class="col-md-4"><input name="cheque_no" class="form-control" placeholder="Cheque no."></div><div class="col-md-4"><input name="cheque_bank" class="form-control" placeholder="Bank"></div><div class="col-md-4"><input name="cheque_date" type="date" class="form-control" value="<?=e($today)?>"></div></div></div>
<div class="col-12"><input name="narration" class="form-control" placeholder="Reference / narration"></div>
<div class="col-12"><button class="btn btn-primary">Post Payment</button></div></div></form></div></div>
<div class="card shadow-sm"><div class="card-header">Payment History</div><div class="card-body"><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Doc</th><th>Date</th><th>Supplier</th><th>Amount</th><th>Method</th><th>Source</th><th>Status</th><th></th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<script>
$(function(){const b=<?=json_encode(url('/'))?>;function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}function esc(v){return $('<div>').text(v??'').html();}function load(){const q={from:$('#from').val(),to:$('#to').val()};$.getJSON(b+'payments/data',q,r=>{const x=$('#rows').empty();(r.data.rows||[]).forEach(a=>x.append('<tr><td>'+esc(a.doc_no)+'</td><td>'+esc(a.payment_date)+'</td><td>'+esc(a.party_name)+'</td><td>'+Number(a.amount).toFixed(2)+'</td><td>'+esc(a.method)+'</td><td>'+esc(a.source)+'</td><td>'+esc(a.status)+'</td><td>'+(a.status==='POSTED'?'<button class="btn btn-sm btn-outline-danger void" data-id="'+a.id+'">Void</button>':'')+'</td></tr>'));});}$('#method').on('change',()=>$('.cheque').toggleClass('d-none',$('#method').val()!=='CHEQUE'));$('#search').on('input',function(){let q=this.value;if(q.length<2)return;$.getJSON(b+'payments/suppliers',{q},r=>{$('#party').empty();(r.data||[]).forEach(a=>$('#party').append(new Option(a.code+' - '+a.name,a.id)));});});$('#form').on('submit',function(e){e.preventDefault();$.post(b+'payments',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){this.reset();load();}}).fail(x=>msg(x.responseJSON?.message||'Payment failed.','danger'));});$('#rows').on('click','.void',function(){const reason=prompt('Void reason');if(!reason)return;$.post(b+'payments/void',{id:$(this).data('id'),reason}).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok)load();});});load();});
</script>