<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Auth; use App\Core\Request; use App\Core\Response; use App\Core\Validator; use App\Core\View; use App\Repositories\CylinderRepository; use App\Services\AuditService; use App\Services\CodeGenerator;
final class CylinderController {
 public function __construct(private readonly CylinderRepository $repo, private readonly CodeGenerator $codes, private readonly Auth $auth, private readonly Request $request, private readonly Validator $validator, private readonly AuditService $audit) {}
 public function index(): Response { return View::render('cylinders/index',['pageTitle'=>'Cylinders','user'=>$this->auth->user(),'_base_path'=>base_path()]); }
 public function data(): Response { $i=$this->request->input(); return Response::json(['ok'=>true,'data'=>$this->repo->paginate(trim((string)($i['search']??'')),(int)($i['group_id']??0),min(100,max(10,(int)($i['limit']??25))),max(0,(int)($i['offset']??0)))]); }
 public function store(): Response { $d=$this->request->input();$e=$this->validator->validate($d,['group_id'=>['required'],'gas_kg'=>['required'],'condition_code'=>['required']]);if($e)return Response::json(['ok'=>false,'message'=>'Validation failed','errors'=>$e],422);$g=$this->repo->rawGroup((int)$d['group_id']);if(!$g)return Response::json(['ok'=>false,'message'=>'Cylinder group not found.'],404);if(bccomp((string)$d['gas_kg'],'0.000',3)<0||bccomp((string)$d['gas_kg'],(string)$g['capacity_kg'],3)>0)return Response::json(['ok'=>false,'message'=>'Gas must be between 0 and cylinder capacity.'],422);$u=$this->auth->user();$d['uid']=(int)$u['id'];$d['notes']=$d['notes']??null;$d['code']=$this->codes->nextCylinderCode((int)$d['group_id'],(string)$g['code'],(string)($d['code_mode']??'AUTO'),(string)($d['code']??''));try{$id=$this->repo->create($d);$this->audit->record((int)$u['id'],'CREATE','cylinders',$id,null,$d,$this->request->ip());return Response::json(['ok'=>true,'data'=>['id'=>$id,'code'=>$d['code']],'message'=>'Cylinder saved']);}catch(\Throwable){return Response::json(['ok'=>false,'message'=>'Cylinder code already exists or data is invalid.'],422);}}
}