<?php
declare(strict_types=1);
namespace App\Controllers;
use App\Core\Auth;use App\Core\Request;use App\Core\Response;use App\Core\Validator;use App\Core\DB;use App\Services\PosService;use App\Services\RateService;
final class PosController {
 public function __construct(private readonly PosService $pos,private readonly RateService $rates,private readonly DB $db,private readonly Auth $auth,private readonly Request $request,private readonly Validator $validator){}
 public function index():Response{return \App\Core\View::render('pos/index',['pageTitle'=>'Point of Sale','user'=>$this->auth->user(),'_base_path'=>base_path()]);}
 public function cylinders():Response{$q=$this->request->query();$group=(int)($q['group_id']??0);$rows=$this->db->fetchAll("SELECT c.id,c.code,c.group_id,c.gas_kg,c.location,c.customer_id,c.condition_code,cg.code group_code,cg.name group_name,cg.capacity_kg FROM cylinders c JOIN cylinder_groups cg ON cg.id=c.group_id WHERE c.active=1 AND c.condition_code='GOOD' AND c.location='SHOP' ".($group?" AND c.group_id=:g":"")." ORDER BY c.code", $group?['g'=>$group]:[]);return Response::json(['ok'=>true,'data'=>$rows]);}
 public function customers():Response{$q=trim((string)($this->request->query()['q']??''));$rows=$this->db->fetchAll("SELECT id,code,name,allow_credit,credit_limit,opening_balance FROM parties WHERE party_type='CUSTOMER' AND active=1 AND (name LIKE :q OR code LIKE :q OR phone LIKE :q) ORDER BY name LIMIT 30",['q'=>'%'.$q.'%']);return Response::json(['ok'=>true,'data'=>$rows]);}
 public function store():Response{$d=$this->request->input();$user=$this->auth->user();try{$lines=json_decode((string)($d['lines_json']??'[]'),true,512,JSON_THROW_ON_ERROR);$result=$this->pos->post(['txn_date'=>(string)($d['txn_date']??date('Y-m-d')),'customer_id'=>(int)($d['customer_id']??0),'counter_id'=>(int)($d['counter_id']??($user['default_counter_id']??0)),'method'=>(string)($d['method']??'CASH'),'received_amount'=>(string)($d['received_amount']??'0.00'),'lines'=>$lines],(int)$user['id']);return Response::json(['ok'=>true,'data'=>$result,'message'=>'Sale posted']);}catch(\Throwable $e){return Response::json(['ok'=>false,'message'=>$e->getMessage()],422);}}
}