<div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-1">Rate Configuration</h1><p class="text-secondary mb-0">Effective-dated gas and cylinder prices.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Add Rate</button></div>
<div id="msg" class="alert d-none"></div>
<div class="card shadow-sm"><div class="card-body"><div class="row g-2 mb-3"><div class="col-md-4"><select id="filterGroup" class="form-select"><option value="0">All cylinder groups</option></select></div><div class="col-md-3"><input id="filterDate" type="date" class="form-control"></div></div><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Group</th><th>Effective Date</th><th>Gas Rate / kg</th><th>Cylinder Price</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="modal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5>Add Rate</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select name="group_id" id="group" class="form-select mb-2" required></select><input name="effective_date" class="form-control mb-2" type="date" required><input name="gas_rate" class="form-control mb-2" inputmode="decimal" placeholder="Gas rate / kg" required><input name="cylinder_price" class="form-control mb-2" inputmode="decimal" value="0.00" placeholder="Cylinder price" required><textarea name="notes" class="form-control" placeholder="Notes"></textarea></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<script>
$(function(){
const b=<?=json_encode(url('/'))?>;
function esc(v){return $('<div>').text(v??'').html();}function msg(t,c='success'){$('#msg').removeClass('d-none alert-success alert-danger').addClass('alert-'+c).text(t);}
function loadGroups(){$.getJSON(b+'cylinder-groups/data',{limit:100},r=>{const s=$('#group').empty(),f=$('#filterGroup');f.find('option:not(:first)').remove();(r.data.rows||[]).forEach(x=>{s.append(new Option(x.code+' - '+x.name+' ('+x.capacity_kg+' kg)',x.id));f.append(new Option(x.code+' - '+x.name,x.id));});});}
function load(){$.getJSON(b+'rates/data',{group_id:$('#filterGroup').val(),effective_date:$('#filterDate').val(),limit:100},r=>{const x=$('#rows').empty();(r.data.rows||[]).forEach(a=>x.append('<tr><td>'+esc(a.group_code+' - '+a.group_name)+'</td><td>'+esc(a.effective_date)+'</td><td>'+Number(a.gas_rate).toFixed(2)+'</td><td>'+Number(a.cylinder_price).toFixed(2)+'</td><td>'+esc(a.active?'Active':'Inactive')+'</td></tr>'));});}
$('#filterGroup,#filterDate').on('change',load);$('#form').on('submit',function(e){e.preventDefault();$.post(b+'rates',$(this).serialize()).done(r=>{msg(r.message,r.ok?'success':'danger');if(r.ok){bootstrap.Modal.getInstance(document.getElementById('modal')).hide();this.reset();load();}}).fail(x=>msg(x.responseJSON?.message||'Save failed','danger'));});
loadGroups();load();
});
</script>