<div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h3 mb-1">Rate Configuration</h1><p class="text-secondary mb-0">Effective-dated gas and cylinder prices by group.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal">Add Rate</button></div>
<div class="card shadow-sm"><div class="card-body"><div class="row g-2 mb-3"><div class="col-md-4"><select id="groupFilter" class="form-select"><option value="0">All groups</option></select></div><div class="col-md-3"><input id="dateFilter" type="date" class="form-control"></div><div class="col-md-2"><button id="refresh" class="btn btn-outline-primary w-100">Refresh</button></div></div><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Group</th><th>Effective Date</th><th>Gas Rate</th><th>Cylinder Price</th><th>Status</th></tr></thead><tbody id="rows"></tbody></table></div></div></div>
<div class="modal fade" id="modal" tabindex="-1"><div class="modal-dialog"><form class="modal-content" id="form"><div class="modal-header"><h5 class="modal-title">Add Rate</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><select name="group_id" id="group" class="form-select mb-2" required><option value="">Select cylinder group</option></select><input name="effective_date" class="form-control mb-2" type="date" required><input name="gas_rate" class="form-control mb-2" inputmode="decimal" placeholder="Gas rate / kg" required><input name="cylinder_price" class="form-control" inputmode="decimal" value="0.00" placeholder="Cylinder price" required></div><div class="modal-footer"><button class="btn btn-primary">Save</button></div></form></div></div>
<script>
$(function(){
 const b=<?=json_encode(url('/'),JSON_THROW_ON_ERROR)?>;
 function esc(v){return $('<div>').text(v??'').html();}
 function loadGroups(){return $.getJSON(b+'cylinder-groups/data',{limit:100}).done(r=>{let a=$('#groupFilter').empty().append(new Option('All groups','0')),s=$('#group').empty().append(new Option('Select cylinder group',''));(r.data.rows||[]).forEach(g=>{a.append(new Option(g.code+' - '+g.name,g.id));s.append(new Option(g.code+' - '+g.name,g.id));});});}
 function load(){return $.getJSON(b+'rates/data',{group_id:$('#groupFilter').val(),effective_date:$('#dateFilter').val(),limit:100}).done(r=>{let x=$('#rows').empty();(r.data.rows||[]).forEach(v=>x.append('<tr><td>'+esc(v.group_code+' - '+v.group_name)+'</td><td>'+esc(v.effective_date)+'</td><td>'+Number(v.gas_rate).toFixed(2)+'</td><td>'+Number(v.cylinder_price).toFixed(2)+'</td><td>'+ (v.active?'Active':'Inactive')+'</td></tr>'))})}
 $('#refresh,#groupFilter,#dateFilter').on('click change',load);
 $('#form').submit(function(e){e.preventDefault();$.post(b+'rates',$(this).serialize()).done(r=>{alert(r.message);if(r.ok){bootstrap.Modal.getOrCreateInstance(document.getElementById('modal')).hide();this.reset();load()}}).fail(x=>alert(x.responseJSON?.message||'Save failed'))});
 loadGroups().done(load);
});
</script>